###
GET http://localhost:9090/vra/compute/iaas/api/machines.do
Content-Type:  application/json
Accept: application/json
###

###
GET http://localhost:9090/vra/deployment/iaas/api/deployments.do
Content-Type:  application/json
Accept: application/json
###

###
GET http://localhost:9090/vra/compute/iaas/api/machine.do?id=8e57e61b9c4e7255
Content-Type:  application/json
Accept: application/json
###

GET http://localhost:9090/vra/blueprint/api/blueprints.do
Content-Type:  application/json
Accept: application/json
###
POST http://localhost:9090/vra/login.do

###

###
POST https://vra.bi.co.kr/csp/gateway/am/api/login
Content-Type:  application/json
Accept: application/json

{
"username" : "admin",
"password" : "admin123!Q"
}

###

###
POST https://vra.vmkloud.com/csp/gateway/am/api/login
Content-Type:  application/json
Accept: application/json

{
  "username" : "injeinc",
  "password" : "vkxmsjdlswo1!"
}

###

###
POST  https://vrops.vmkloud.com/api/auth/token/acquire
Content-Type:  application/json
Accept: application/json

{
  "username" : "injeinc",
  "password" : "vkxmsjdlswo1!"
}

###